### ISSUE TITLE
Upgrade from 4.0.7 to 4.1.0 not possible

### ISSUE THREAD

**Issue by ZuSe** [zammad/zammad-helm#101]
It throws. Seems like sth. in the template is broken.

zammad$ helm upgrade zammad zammad/zammad -f values.yaml
coalesce.go:165: warning: skipped value for extraEnv: Not a table.
Error: UPGRADE FAILED: template: zammad/templates/ingress.yaml:45:21: executing "zammad/templates/ingress.yaml" at <.path>: can't evaluate field path in type interface {}

**Comment by monotek** [comment]
https://github.com/zammad/zammad-helm/blob/master/zammad/README.md#from-zammad-35x-to-4x

**Comment by ZuSe** [comment]
Hi @monotek 

as I wrote, I am already on 4.0.7, not 3.x

**Comment by ZuSe** [comment]
I solve it by dumping the db and restoring it after clean install.

**Comment by monotek** [comment]
The docs are about the chart version not the docker image tag.
