### ISSUE TITLE
[FR] Support Redis with user

### ISSUE THREAD

**Issue by ZuSe** [zammad/zammad-helm#119]
Right now it is not possible to specify an external redis that requires to provide a user.
However, redis introduces with 6.x  support for different users (and privs).

Many cloud vendors tend to only offer Redis as a Service with custom users, without providing any fallback for the old connection strings. Therefore I ask to support redis usernames as input parameter similar as it is already supported for psql or elastic search

https://github.com/zammad/zammad-helm/blob/main/zammad/templates/statefulset.yaml

**Comment by MrGeneration** [comment]
Zammad does not support this as an upstream application and thus this feature request is not solvable by this repository.
See: https://docs.zammad.org/en/latest/appendix/configure-env-vars.html#performance-tuning

Please create a feature request on the Zammad community: https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6

I'll be closing this issue as it's not fixable right now.
