### ISSUE TITLE
postgresql.postgresqlUsername is in the values file, but isn't used in the chart

### ISSUE THREAD

**Issue by bjornskovlund** [zammad/zammad-helm#134]
**What happened**:
I tried to use postgresql.postgresqlUsername

**What you expected to happen**:
The services would try to connect to (externally deployed) database with this username, but it still attempts to connect as "postgres" user.

**Anything else we need to know**:
Searching your repo, "postgresqlUsername" is only found in values.yaml and README.md

**Comment by bjornskovlund** [comment]
I found out you use the zammadConfig.postgresql.user instead. I had some other issues that threw me off a bit. Still not super user friendly.

**Comment by MrGeneration** [comment]
The Readme holds all relevant user variables that might help you:
https://github.com/zammad/zammad-helm/blob/main/zammad/README.md
