### ISSUE TITLE
health check problems with helm chart 6.7.0

### ISSUE THREAD

**Issue by rmuehlbauer** [zammad/zammad-helm#137]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 3.9 / Kubernetes 1.22

**What happened**:
Since upgrading the zammad helm chart from 6.6.0 to 6.7.0 the Monitoring inside Zammad (Admin --> Monitoring (under System) tells me `scheduler may not run (last execution of Stats.generate about 2 months ago) - please contact your system administrator`.

![image](https://user-images.githubusercontent.com/38917808/176483436-8bdd50d7-2019-49ff-ad3b-8588c9bdc5de.png)

I'm also using the provided healthcheck url in our monitoring system, to check zammads health and of course I'm also getting alarms there.

When I look in the scheduler pods log file, its not looking too bad - at least theres some ok looking activity there:
```
I, [2022-06-29T15:58:01.015498 #1-109200]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2022-06-29T15:58:01.017337 #1-109200]  INFO -- : ended Channel.fetch took: 0.018719892 seconds.
I, [2022-06-29T15:58:31.026244 #1-109200]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2022-06-29T15:58:31.027890 #1-109200]  INFO -- : ended Channel.fetch took: 0.007268574 seconds.
I, [2022-06-29T15:59:01.034358 #1-109200]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2022-06-29T15:59:01.035733 #1-109200]  INFO -- : ended Channel.fetch took: 0.006543665 seconds.
I, [2022-06-29T15:59:13.740571 #1-108860]  INFO -- : ProcessScheduledJobs running...
I, [2022-06-29T15:59:13.748378 #1-120320]  INFO -- : execute ImportJob.start_registered (try_count 0)...
I, [2022-06-29T15:59:13.752938 #1-120320]  INFO -- : ended ImportJob.start_registered took: 0.009868007 seconds.
I, [2022-06-29T15:59:23.752695 #1-108860]  INFO -- : Running job thread for 'Process ticket escalations.' (Ticket.process_escalation) status is: sleep
I, [2022-06-29T15:59:31.043167 #1-109200]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2022-06-29T15:59:31.044938 #1-109200]  INFO -- : ended Channel.fetch took: 0.008018813 seconds.
I, [2022-06-29T15:59:33.762666 #1-108860]  INFO -- : Running job thread for 'Check 'Channel' streams.' (Channel.stream) status is: sleep
I, [2022-06-29T15:59:43.770872 #1-120400]  INFO -- : execute Ticket.process_pending (try_count 0)...
I, [2022-06-29T15:59:43.973586 #1-120400]  INFO -- : ended Ticket.process_pending took: 0.208151392 seconds.
I, [2022-06-29T15:59:53.780674 #1-120540]  INFO -- : execute Ticket.process_auto_unassign (try_count 0)...
I, [2022-06-29T15:59:53.784191 #1-120540]  INFO -- : ended Ticket.process_auto_unassign took: 0.008527539 seconds.
I, [2022-06-29T16:00:01.052044 #1-109200]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2022-06-29T16:00:01.053573 #1-109200]  INFO -- : ended Channel.fetch took: 0.00745371 seconds.
I, [2022-06-29T16:00:03.785260 #1-108860]  INFO -- : Running job thread for 'Check channels.' (Channel.fetch) status is: sleep
I, [2022-06-29T16:00:09.836285 #1-109540]  INFO -- : execute Job.run (try_count 0)...
I, [2022-06-29T16:00:09.838140 #1-109540]  INFO -- : ended Job.run took: 0.010392464 seconds.
I, [2022-06-29T16:00:13.795866 #1-120640]  INFO -- : execute SessionTimeoutJob.perform_now (try_count 0)...
I, [2022-06-29T16:00:13.859815 #1-120640]  INFO -- : SessionTimeoutJob removed session '36821947' for user id '' (last ping: '', timeout: '-1')
```
May this issue somewhat be associated with the recent switch from scheduler to background-worker?

**What you expected to happen**:
Zammad health check should report actual system status

**How to reproduce it** (as minimally and precisely as possible):
Just use helmchart 6.7.0 to setup a zammad instance and you should see the health check issue

**Anything else we need to know**:

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
This topic is not helm or docker specific.
Please refer the Zammad community over at: https://community.zammad.org .

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by MrGeneration** [comment]
> Are you really sure, that this has nothing to do with the issue I'm experiencing?

No of course not. I'm always just digging in the dark and am here for annoying people with answers.
Especially because Zammads monitoring tells you one of it's jobs is due by two months. /s

I suggest you read the release notes and learn why this change has been done.
But I also have good news for you: This is the last public answer and action I'm doing in one of Zammads repository. I've had enough of all the questionings in the past days and weeks. Have a great day.

**Comment by monotek** [comment]
Imho not related. 
The service works. Otherwise it would be in a crashloop.
If its a problem it's non of the Helm chart but of Zammad itself and therfore the issue would need to be created in: https://github.com/zammad/zammad
