### ISSUE TITLE
FR: Running elasticsearch reindex after service is ready

### ISSUE THREAD

**Issue by ohemelaar** [zammad/zammad-helm#145]
Is this a BUG REPORT or FEATURE REQUEST? (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: n/a

**What happened**:
When deploying with a large amount of existing tickets, the reindex step in elasticsearch-init can take a very long time. Because it's run in an init container, the service isn't available during that time.

I see [there is a way to disable the reindex](https://github.com/zammad/zammad-helm/pull/60), although I guess it would still be necessary to run it manually once the service is deployed.

**What you expected to happen**:
Thus, I thought that by leveraging [Helm chart hooks](https://helm.sh/docs/topics/charts_hooks/) it could be possible to run the reindex after the service has restarted and is available again to avoid long downtimes and doing a manual action to reindex.

I mostly wondered if there is something in zammad or elasticsearch that prevents running the reindex out of bound? If not, I should be able to make a PR for this.

**How to reproduce it** (as minimally and precisely as possible): n/a

**Anything else we need to know**:

**Comment by monotek** [comment]
https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml#L55

**Comment by ohemelaar** [comment]
Hi @monotek 
I saw this option, this is what I mentionned by referring to #60 . My feature request was to know if instead of disabling it it could be possible to run it after the service is ready? Or are there significant downsides to doing that?
Thanks

**Comment by MrGeneration** [comment]
It's not a feature request but a technical question. You can run reindexing at any time. Just have a look into the documentation.

**Comment by ohemelaar** [comment]
Yes, sorry for the confusion, I tried to make sure my FR was not nonsense. This question was a primer to the feature request which is to actually run the reindex automatically after the service is ready using Helm chart hooks. Does that look like a good idea? If so, I could work on a PR if you want.

**Comment by MrGeneration** [comment]
I can't qualify that as I don't understand the goal / take / difference.
What I know is that, by default, Zammad will reindex on every compose restart (that'd affect kubernetes as well).

What I understand is that you're trying to add something that already exists or I don't understand the scope.

**Comment by ohemelaar** [comment]
I'll try to explain my whole thought process, so maybe you can see if I'm making incorrect assumptions at some point.

I've noticed that during restart, the elasticsearch reindex step took a lot of time (about 30min in my case, I saw another issue reporting around an hour). Because by default it happens in an init container, the service is down during this time and people can't access tickets.

There is the option to disable the reindex, but I guess it is run by default for a reason. I wouldn't want to have the search broken silently when deploying an update. If that happens I'd have to spot the potential issue myself or be warned by the users to run the reindex manually.

So, I thought that disabling reindex in the init container, and running it after in a job with helm hook could allow faster start times while still ensuring that reindexing always runs when upgrading the helm release.

**Comment by MrGeneration** [comment]
That change would nuke docker compose based installations so I'm afraid that's a no can do.
The reindex runs automatically as a convenience feature to ensure your index is always up to date and compatible.

It is absolutely not required to do so if you read release notes.
In my personal opinion docker compose and kubernetes is not exactly production ready and might introduce down sides for you. We at Zammad have very little to no kubernetes and docker knowledge which is why monotek is in charge in those repos and we're explicitely pointing out only application level support on said installation types.

I'm afraid that's the part where I'm getting off the train.

**Comment by monotek** [comment]
A Helm hook has no influence to docker-compose setups.
The Helm and docker-compose setups using the same container but not even the  same docker entrypoint, which is overwritten in k8s by a configmap.

But i'm not sure if a helm hook is the way to go here too.
I could even be done by hand as it's not realy needed, this often, beside initial setup and if some breaking change would be in a major version update.

Maybe a (cron)job could do the trick too.

Not sure if we have some schema version flag in elasticsaerch so we could even automate major version updates completly.
