### ISSUE TITLE
issue with nginx worker_processes

### ISSUE THREAD

**Issue by Freundschaft** [zammad/zammad-helm#168]
when I run the latest version 8.0.2, i receive the following error:

`nginx: [emerg] "worker_processes" directive is not allowed here in /etc/nginx/sites-enabled/nginx.conf:1`

**Comment by monotek** [comment]
Weird, i don´t seee this error. 

It's configured in the nginx.conf, like in the example of the official docs: https://www.nginx.com/resources/wiki/start/topics/examples/full/

**Comment by Freundschaft** [comment]
i downgraded to a lower version and upgradedf again and the issue just magically resolved itself
