### ISSUE TITLE
Unable to start redis & postgresql statefulset

### ISSUE THREAD

**Issue by sanasz91mdev** [zammad/zammad-helm#169]
Getting following error in pod/statefulset logs

```
kubectl logs pod/zammad-redis-master-0
1:C 24 Jan 2023 20:19:10.813 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 24 Jan 2023 20:19:10.813 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 24 Jan 2023 20:19:10.813 # Configuration loaded
1:M 24 Jan 2023 20:19:10.815 * monotonic clock: POSIX clock_gettime
1:M 24 Jan 2023 20:19:10.816 # Can't open the append-only file: Permission denied
```

also i have already given permissions to redis PV folder. 

` sudo chown -R 1001:1001 /redisPvFolder`

**Comment by monotek** [comment]
Can't reproduce with our default setttings:

```
 k logs -f zammad-redis-master-0
1:C 25 Jan 2023 13:42:11.475 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 25 Jan 2023 13:42:11.475 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 25 Jan 2023 13:42:11.475 # Configuration loaded
1:M 25 Jan 2023 13:42:11.476 * monotonic clock: POSIX clock_gettime
1:M 25 Jan 2023 13:42:11.476 * Running mode=standalone, port=6379.
1:M 25 Jan 2023 13:42:11.476 # Server initialized
1:M 25 Jan 2023 13:42:11.478 * Creating AOF base file appendonly.aof.1.base.rdb on server start
1:M 25 Jan 2023 13:42:11.479 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
1:M 25 Jan 2023 13:42:11.479 * Ready to accept connections
```

If you use special redis settings, like persistence, you might need to adjust the pod securitycontext too, to use fsGroup setting.

**Comment by monotek** [comment]
What kind of kubernetes do you use?
Some managed cloud provider or bare metal?

`zammadConfig.initContainers.postgresql.securityContext.privileged=true` should not be needed.

**Comment by sanasz91mdev** [comment]
> Loading custom pre-init scripts

i am using baremetal currently. My PV is Bound to PVC created by zammad helm


PV: 

`Name:            hostpath-redis
Labels:          type=local
Annotations:     pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    manual-postgre
Status:          Bound
Claim:           zammad/data-zammad-postgresql-0
Reclaim Policy:  Retain
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        8Gi
Node Affinity:   <none>
Message:
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /redis
    HostPathType:
Events:            <none>`

**Comment by sanasz91mdev** [comment]
> > Loading custom pre-init scripts



> zammadConfig.initContainers.postgresql.securityContext.privileged=true

Without above postgre was giving same error

**Comment by monotek** [comment]
Thats likely because you're trying to create directories in the k8s host filesystem level of: "/".

```
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /postgre
```

I would go for some directory owned by non root user.

I fear this is a support request we can't cover. 
Thats has nothing to do with zammad but the way you run your k8s.

**Comment by sanasz91mdev** [comment]
> Thats likely because you're trying to create directories in the k8s host filesystem level of: "/".
> 
> ```
> Source:
>     Type:          HostPath (bare host directory volume)
>     Path:          /postgre
> ```
> 
> I would go for some directory owned by non root user.
> 
> I fear this is a support request we can't cover. Thats has nothing to do with zammad but the way you run your k8s.

I tried it by changing owner too. Can you guide what else i could do?

`drwxrwxrwx.   2  1001  1001   28 Jan 25 18:02 postgre`

**Comment by monotek** [comment]
No

**Comment by sanasz91mdev** [comment]
Ok ... you may then close this issue if this is not related to zammad helm @monotek
