### ISSUE TITLE
Increasing the Indexing Speed / Count

### ISSUE THREAD

**Issue by abhi15behera** [zammad/zammad-helm#186]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**: 1.24

**What happened**: Indexing of 100 tickets take 10 sec approximately at a given interval. Can this be increased instead of 100 to  300 to 500 tickets for the same interval. If yes do we need to make change on the ES or on the Postgres in order to do that or that can we configured from Zammad Rail

**What you expected to happen**: Indexing speed should be more than 100 Tickets at a interval

**How to reproduce it** (as minimally and precisely as possible):

Setup an External Elasticsearch (8.5.1) connect with an External Postgres Cluster and Zammad App- 8.2.2 and set the Heap Size atleast 10G along with JVM Parameter as 10G

**Anything else we need to know**:

**Comment by MrGeneration** [comment]
Indexing happens in order and thus there is no such thing as increasing from 100 to 200 as example.
The searchindex process just reports in 100 steps to give you feedback about the state.

There's an environment that stops docker from constantly re-indexing on restarts (which is useless on big environments -especially- if you have proper control over your environment). Keep in mind that you have to reindex on your own.

**Comment by abhi15behera** [comment]
@MrGeneration Thank you for the information. With that said Tweaking all the parameter on Elasticsearch or Postgres doesnt just increases the steps. Because we have almost 1.1 Million tickets and re-indexing those take almost a minimum of 6-7 Hours. As per helm i have set the re-indexing to false so that upon restart of the zammad app pod doesnt re build the indexing as it will again take 6-7 Hours. Is there a method to reduce the Doc counts in Elasticsearch as i understand the "Zammad_production_ticket" is where all the ticket get indexed. Even if the tickets are closed we still might need to have that in the elastic in order to be fetched during the search in Zammad.

**Comment by mgruner** [comment]
Hi @abhi15behera, if I understand your request correctly, it is not about zammad-helm, but instead about the Zammad product itself. Please head over to https://community.zammad.org/ to ask questions or place feature requests, or get in touch with us via zammad.com if you require commercial support.
