### ISSUE TITLE
Storage path after upgrade zammad to 6.X

### ISSUE THREAD

**Issue by alexkorotysh** [zammad/zammad-helm#196]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes: 1.24
Helm: 3.12.1
Zammad helm chart version: 9.0.3
Zammad version: 6.0.0-32

**What happened**:
 Upgraded zammad installation with helm chart from 8.3.1 to 9.0.3

**What you expected to happen**:
Successful upgrade, but after upgrade, PVC was changed path, and now /opt/zammad/var, but all files kept in /opt/zammad/storage/fs, so looks like after recreating zammad container if we use the filesystem as storage we lost data?

**How to reproduce it** (as minimally and precisely as possible):
Install zammad with helm chart with version 9.0.3

**Anything else we need to know**:

I don't understand why it was changed, cause according to zammad documentation 
https://docs.zammad.org/en/latest/admin/console/zammad-settings.html?highlight=storage#storage-provider-setting
Filesystem (/opt/zammad/storage/)

And my question how we should serve files if we cant' change default path for storage and how to fix it?

**Comment by alexkorotysh** [comment]
my thinks about it:
1. we should add one more pvc for storage and mount as /opt/zammad/storage ? 
2. we should add into zammad-init container creating symlink for /opt/zammad/storage  and pointing to /opt/zammad/var/storage ? I'm not sure if it will work. 
3. I'm not sure about these questions because I don't understand what we should use /opt/zammad/var folder/vpc

 As I see zammad-docker-compose repo comment https://github.com/zammad/zammad-docker-compose/issues/348#issuecomment-1609716709

Users recommend map folder for storage

**Comment by rmuehlbauer** [comment]
i had exactly the same issue: https://github.com/zammad/zammad-helm/issues/194
I think by mistake it was identified as a duplicate to another postgresql error and therefore closed - in the end I believe that my issue and this issue here have the same reason ... 

As I configured zammad to store all the email attachments not within the database but in the filesystem (under /opt/zammad/storage) I would prefer to have a separate filesystem here, like it was before

**Comment by mvella42** [comment]
I'm still confused by this, as to whether or not the upgrade succeeds if we are using file storage (we are).

Right now, we're running 8.3.1 with lots of file storage (40+GB), I and would like to upgrade to 9.0.3 but I'm not certain if the upgrade will work, and so am uncertain about proceeding.

I momentarily considered changing from file storage to DB storage, doing the upgrade, and then going back again, but aside from the space considerations, I'm certain it would take days!

So has anyone successfully upgraded and had their file storage preserved through the process?

**Comment by alexkorotysh** [comment]
@mvella42 Right now it's impossible to upgrade safely. Wait for a stable release chart and do backups of your storage regularly.

**Comment by mvella42** [comment]
Thanks @alexkorotysh will do

**Comment by monotek** [comment]
I've created an pr which hopefully workarouds the issue: https://github.com/zammad/zammad-helm/pull/197

You might test it via my branch: https://github.com/monotek/zammad-helm/tree/storage

**Comment by alexkorotysh** [comment]
Hello @monotek, thanks for the feedback, but I think that unfortunately a dirty fix. 
From my perspective I don't see the:
1. Flexibility. How about the size for storage PVC? Will we have the same size for **var** and **storage** PVC? What about another annotation? Like storageClass and accessModes? Looks like we need to change values.yml with new structure for PVC. 
2. After updating we will have problems with initialization, causing the new PVC will be empty, without storing data. (but probably we can't do smt with it.).

**Comment by monotek** [comment]
Thats the reason i've said it's a workaround and not a fix.
The fix has to happen in zammads storagehandling itself and not the helmchart.

**Comment by alexkorotysh** [comment]
S3 is dream, zammad without PVC is ideal dream

**Comment by monotek** [comment]
I'll try to adjust the pvc config in the next days, so we have at least the workaround released.

**Comment by rmuehlbauer** [comment]
> I'll try to adjust the pvc config (#197) in the next days, so we have at least the workaround released.

I absolutely would appreciate this! 
I'm using the option to store attachments in a pvc ever since and for me the helm chart is unusable since the changes to the pvc...

**Comment by monotek** [comment]
I decided to keep the change as small as possible so the new var dir will be mounted to the storage dir too.
So we don't need an additional voluime at all.
