### ISSUE TITLE
UPGRADE FAILED: no Secret with the name "zammad-postgresql-pass" found

### ISSUE THREAD

**Issue by snics** [zammad/zammad-helm#20]
**Is this a request for help?**:
Unfortunately the update does not work. Unfortunately I always get the error message:
Failed to install app zammad. Error: UPGRADE FAILED: no Secret with the name "zammad-postgresql-pass" found

The secret is there, though.

thank you it is due to this error:
https://github.com/zammad/zammad-helm/blob/9225548155182e1dd51d10a740fd3dfac62c44a4/zammad/templates/statefulset.yaml#L44
https://github.com/zammad/zammad-helm/blob/9225548155182e1dd51d10a740fd3dfac62c44a4/zammad/templates/secrets.yaml#L4
---

**Is this a BUG REPORT**

**Version of Helm and Kubernetes**:  
```
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
```
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```
**What happened**:
After an update helmet always bleaches with the error message "Failed to install app zammad. Error: UPGRADE FAILED: no Secret with the name "zammad-postgresql-pass" found" but unfortunately this is not correct.

**How to reproduce it** (as minimally and precisely as possible):
Update from version 1.0.0 to 1.0.2.

**Comment by monotek** [comment]
What's the output of:

kubectl get secrets

**Comment by monotek** [comment]
I'm also not able to reproduce it. Update from 1.0.0 to 1.0.2 worked...

**Comment by snics** [comment]
```
zammad-elasticsearch-client-token-gxm6d   kubernetes.io/service-account-token   3      46d
zammad-elasticsearch-data-token-29jnv     kubernetes.io/service-account-token   3      46d
zammad-elasticsearch-master-token-kbz5g   kubernetes.io/service-account-token   3      46d
zammad-postgresql                         Opaque                                1      11d
zammad-postgresql-pass                    Opaque                                1      11d
zammad-tls                                kubernetes.io/tls                     3      46d
```

but this is only for the namespace `zammad`

**Comment by monotek** [comment]
So the secret "zammad-postgresql-pass" is there.
In the current version this seems already to be fixed.
Please try to update with --force option.

**Comment by snics** [comment]
Yes, I did. Removed before I updated it only unfortunately that did not work either

**Comment by snics** [comment]
But I also use Rancher's UI so everyone in the team can update it. Could that be the problem?

**Comment by monotek** [comment]
> Yes, I did. Removed before I updated it only unfortunately that did not work either

Whats teh error message?

> But I also use Rancher's UI so everyone in the team can update it. Could that be the problem?

I don't know. 
I have no Rachner setup.

**Comment by snics** [comment]
> Whats teh error message?
You can see the error message here on the picture in red
![Screenshot 2019-04-03 at 13 08 15](https://user-images.githubusercontent.com/8299486/55474493-96720b80-5611-11e9-8e1f-0d268fd35ac2.png)

> I don't know.
> I have no Rachner setup.
Okay, so I'm gonna go check it out. But as far as I know, it shouldn't be a problem.

**Comment by monotek** [comment]
Could you please do everything from the command line?

**Comment by zifeo** [comment]
@monotek the issue is that the names differ although they refer to the same resource:

https://github.com/zammad/zammad-helm/blob/master/zammad/templates/secrets.yaml#L4
https://github.com/zammad/zammad-helm/blob/9225548155182e1dd51d10a740fd3dfac62c44a4/zammad/templates/statefulset.yaml#L44

**Comment by monotek** [comment]
ups... totally missed that... 
pull request welcome ;-)
or i'll do it the next days...

**Comment by zifeo** [comment]
@monotek done on https://github.com/zammad/zammad-helm/pull/23
