### ISSUE TITLE
Can not add Logo at setup or in settings

### ISSUE THREAD

**Issue by rhizoet** [zammad/zammad-helm#200]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**: 
Kubernetes: 1.26.6
Helm: 3.12.0
Zammad-helm: 9.0.4

**What happened**:
When I install Zammad and get to the part where I can select a logo, the following error message comes up:
```
Read-only file system @ rb_sysopen - /opt/zammad/public/assets/images/2e8e695017d62bf4d9cbb01703ac55c1.png
```
I have also already set `readOnlyRootFilesystem: false` for all init containers. However, this does not change anything.

**What you expected to happen**:
I assume that I can upload a logo and this will be added to Zammad. There should be no error message that this is a `read-only fs`.

**How to reproduce it** (as minimally and precisely as possible):
Install the current helm chart and try to add a logo during setup. Or in the settings when setup is finished.

**Anything else we need to know**:
![Screenshot_20230713_113854](https://github.com/zammad/zammad-helm/assets/58997736/ff0ef066-05f7-4705-b722-0aa2e668cc24)

**Comment by rhizoet** [comment]
Oh, the Zammad Pod does not come up again if I had done some changes and the GUI states, that I have to restart all the services.

```
Back-off restarting failed container postgresql-init in pod zammad-0_helpdesk(2e98ac3b-66ea-4d5f-b8b2-7b1ab772c321)
```

**Comment by monotek** [comment]
see: https://github.com/zammad/zammad-helm/pull/197

**Comment by rhizoet** [comment]
I'm always get the same error even with the new version of the chart. Can you have a look what's up with the images?

**Comment by rhizoet** [comment]
@monotek can you reopen the issue because it's not fixed?

**Comment by alexkorotysh** [comment]
Any updates with broken logo?

**Comment by monotek** [comment]
will be fixed in: https://github.com/zammad/zammad-helm/pull/215
