### ISSUE TITLE
Cannot upload attachments -  read only file system

### ISSUE THREAD

**Issue by almarbjornsson** [zammad/zammad-helm#203]
**Is this a request for help?**:
Yes, I need help to enable uploading attachments before we deploy Zammad to production
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
RKE2 1.25 
Zammad Helm Chart 9.0.5

**What happened**:
After a fresh installation using chart version 9.0.0, uploading attachments has not worked. Incremental upgrades to version 9.0.5 have not resolved this issue. The issue also exists for uploading avatars.

Error on client side:
```
POST https://{redacted-host}/api/v1/upload_caches/934272618 500 (Internal Server Error)
```
Rails server logs:
```
2023-07-21 10:11:11 +0000 Rack app ("POST /api/v1/upload_caches/934272618" - (10.10.1.200, 10.42.2.103)): Errno::EROFS: Read-only file system @ rb_sysopen - /opt/zammad/tmp/RackMultipart20230721-1-8ykwvi.png
```
**What you expected to happen**:
Expected the system to allow uploads of attachments and avatars.

**How to reproduce it (as minimally and precisely as possible)**:
Install zammad:9.0.5 with defaults. Attempt to upload an attachment on a ticket or upload an avatar.

**Anything else we need to know**:
Switching the storage backend to filesystem did not resolve the issue. This seems to be related to the temporary storage before attachments are moved to their permanent storage location in the database or on the filesystem.

![image](https://github.com/zammad/zammad-helm/assets/113608966/ed9522ed-f1cc-43c0-8033-00e923a8efa3)

**Comment by mgruner** [comment]
@almarbjornsson could you check #215 please? It should solve this issue.
