### ISSUE TITLE
Locales table in PostgreSQL without any record on container creation

### ISSUE THREAD

**Issue by admtargetdata** [zammad/zammad-helm#208]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes v1.26
Helm v3.12.3

**What happened**:
When installing Zammad and its dependencies using the helm in Kubernetes, the tables with the languages were created in the installation of Zammad in Kubernetes, but without any records.

**What you expected to happen**:
That in the standard installation, the table is already loaded in PostgreSQL with the available languages.

**How to reproduce it** (as minimally and precisely as possible):
An installation of Zammad using Helm, following the following commands:

# Add Helm repo
$ helm repo add zammad https://zammad.github.io/zammad-helm

# Install / Upgrade Zammad
$ helm upgrade --install zammad zammad/zammad --namespace=zammad

**Anything else we need to know**:
![Captura de tela 2023-08-31 134825](https://github.com/zammad/zammad-helm/assets/87144231/7a7b3196-eb0e-432e-a950-00118e402bb6)
![Captura de tela 2023-08-31 134735](https://github.com/zammad/zammad-helm/assets/87144231/35768a2c-d4e0-4ea8-94d3-9be9f5599ed5)
![Captura de tela 2023-08-31 134659](https://github.com/zammad/zammad-helm/assets/87144231/656fc0fd-4ae9-4a5b-a20f-d86871ba5d69)

**Comment by MrGeneration** [comment]
I'm closing this issue in favor for the community thread you've created as well.
Please try to focus on one place instead of posting it on as many places as possible. 🙏 

https://community.zammad.org/t/locales-table-in-postgresql-without-any-record-on-container-creation/12118
