### ISSUE TITLE
Backup doesn't works on k8s

### ISSUE THREAD

**Issue by Behoston** [zammad/zammad-helm#21]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:  

- Minikube 1.14.1
- Helm 2.13.1

**What happened**: 
I want to run backup from any zamad container (checked all: railssever, websocket and scheduler).

**What you expected to happen**: 
Backup works from some containers or there is option to configure separate pod that can do backup periodicaly.

**How to reproduce it** (as minimally and precisely as possible):
- deploy zamad on minikube
- exec into any zamad container
- configure backup (rename file and creat backup dir)
- try to do backup

**Anything else we need to know**: -

**Comment by monotek** [comment]
The backup script can't work in containerized zammad installations. It's also not supposed to do that...

You could try to use a tool like velero to do Kubernetes backups: https://github.com/heptio/velero

**Comment by natorus87** [comment]
So i got i working, its not perfect yet, and needs more testing. As a sample, restore was not testet. Here is the Code: https://github.com/natorus87/zammad-helm-backup/tree/main
