### ISSUE TITLE
auto_wizard settings do not work

### ISSUE THREAD

**Issue by mvngne** [zammad/zammad-helm#217]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: 10.0.0
k8s: v1.24.6

**What happened**:
After enabling the autowizard and providing some configuration, the setting seem to have no effekt. On first startup the manual wizard appers, even if the autowizard link gets opend manually (http://zammad/#getting_started/auto_wizard).

**What you expected to happen**:
Automatic configuration of everthing provided in the autowizard config. 

**How to reproduce it** (as minimally and precisely as possible):
Empty k8s namespace or create a new one. Create basic configuration for the helm chart. Deploy. Open zammad web page.

**Anything else we need to know**:
I've tried many times with several settings. The zammad-init container has the environment setting AUTOWIZARD_JSON set and if I take a look into zammand-nginx I can find the auto_wizard.json where it should be (at least I think).

```
zammad@zammad-0:~/var$ ls -al /opt/zammad/var/
total 28
drwxrwsr-x 3 zammad zammad  4096 Sep 27 14:59 .
drwxr-xr-x 1 zammad zammad  4096 Sep 27 15:02 ..
-rw-r--r-- 1 zammad zammad   474 Sep 27 14:59 auto_wizard.json
drwxrws--- 2 zammad zammad 16384 Sep 27 14:58 lost+found
```

**Comment by monotek** [comment]
No, the compose entrypoint is not used.
Instead an own command is defined: 

https://github.com/zammad/zammad-helm/blob/main/zammad/templates/statefulset.yaml#L258

The actual file is created in the init container: 
https://github.com/zammad/zammad-helm/blob/main/zammad/templates/configmap-init.yaml#L36

I guess it's missing in the actual rails container as teh storage is not shared anymore.

I'll create a fix later.

**Comment by mgruner** [comment]
🤦 thanks for the pointer. The file is indeed present, but the ENV `AUTOWIZARD_RELATIVE_PATH` to inform Zammad about its location is not. I'll send a MR later.
