### ISSUE TITLE
BUG/Enhancement - Elastic-search init container

### ISSUE THREAD

**Issue by RegisHubelia** [zammad/zammad-helm#220]
Bug/Enhancement request

  - Currently, when a zammad container start, elasticsearch-init can take a long time to index if you have a lot of data.  
  - On top of that, if you want 2 replicas of zammad, the second replica also re-index all the data.
  - it then takes quite some time when upgrading/changing configuration for the app to be available.  For us it's about 20 minutes per pod - and we have 2 - so about 40 minutes until app/search works as expected.

**What you expected to happen**:
  - The init container should check if elastic search indexes is already initialised and contains data.  If so, ignore re-indexing.
  - Using redis pub/sub to add/remove items from the indexes - my guess is that it's probably already the case as new tickets gets added in the indexes.
  - Scheduled full re-index on a specified/configured cron schedule?

This way, indexing wouldn't block the app availability, and we'd still be quite comfortable with the accuracy of the indexes.

**Comment by MrGeneration** [comment]
This is not a bug but expected behavior.
You may want to check the configuration options you have and adjust your configuration accordingly.

https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml#L57-L68

**Comment by RegisHubelia** [comment]
Ah - thanks, I appreciate the quick response.  Should of check the settings, so glad it's already an option.

**Comment by alexkorotysh** [comment]
@RegisHubelia 
https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml#L66 
set reindex = false to skip reindex each restart pod
If you need you can easily reindex from zammad pod

**Comment by RegisHubelia** [comment]
Thank you.  This worked fine.
