### ISSUE TITLE
Authentication for memcached?

### ISSUE THREAD

**Issue by johanneskastl** [zammad/zammad-helm#224]
**Is this a request for help?**: No.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): More of a feature request.

**Descripotion**

If I am not mistaken there is currently no authentication enabled on the memcached subchart.

1. `auth.enabled` defaults to `false` in the memcached chart.
   https://github.com/bitnami/charts/blob/main/bitnami/memcached/README.md?plain=1#L92

2. There is no memcached section in the `secrets` part of the Zammad `values.yaml`
   https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml#L29

3. There are no auth-related settings in the memcached subchart settings in the Zammad `values.yaml`
   https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml#L431

I can prepare a PR to enable this on the subchart, but I have no idea if it is possible to tell Zammad to actually use authentication when talking to memcached. And, if it is possible, how to do that.

So, before going down that route, I wanted to ask if memcached authentication was disabled intentionally and whether it could be enabled by default.

**Comment by mgruner** [comment]
Hello @johanneskastl. Thanks for your proposal! I believe that Zammad does not support memcached authentication yet. It basically uses the default Rails memcached back end, and [the documentation](https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-memcachestore) does not mention authentication at all.
So I guess this would need to be clarified / added as a first step, after which we could make changes to the Helm chart.

**Comment by mgruner** [comment]
@johanneskastl how do you want to proceed here? Would you like to look into adding memcached authentication in Zammad, or should we close this issue for now?

**Comment by johanneskastl** [comment]
Hi @mgruner I have no idea how to add this feature to Zammad itself, so I would propose to close this for now.

Can we add this as a feature request with the Zammad team, so it gets implemented (or verified if it can be implemented, or if rails just does not allow that)?

**Comment by mgruner** [comment]
Definitely. There are two ways to do that:
- File a feature request at https://community.zammad.org/.
- Get in [touch with the Zammad team](https://zammad.com/en/company/contact) to set up a prioritized commercial project.
