### ISSUE TITLE
Ability to label deployed resources

### ISSUE THREAD

**Issue by xeruf** [zammad/zammad-helm#259]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature

Many other helm charts have the ability to label deployed resources, which we use for our Velero backup system, for example list this:
```sh
    commonLabels:
      stackspin.net/backupSet: "zammad"
    podLabels:
      stackspin.net/backupSet: "zammad"
```
zammad does not seem to honor that, would be great if it did

**Comment by mgruner** [comment]
.

**Comment by xeruf** [comment]
thanks, looks good to em :)
