### ISSUE TITLE
Splitting the services and horizontal scaling

### ISSUE THREAD

**Issue by bjornskovlund** [zammad/zammad-helm#28]
Hi,

Hope it's OK I'm skipping the template, as this is more of an architectural thing.

I've been running Zammad for a couple of months now, in Kubernetes, with a rather high adaptation within our organisation. Both the users and I have been very pleased with the application.

However, the Kubernetes implementation has a lot of lacks, in terms of creating something stable, especially splitting the services inside the zammad statefulset to individual containers. I assume the statefulset does not scale horizontally as it is, right? Assuming the hardcoded `spec.replicas` gives a hint ;)

I'm not very well adversed in Rails, but if there's something I can offer in terms of Kubernetes and Helm charts, I'm happy to help out.

I have a lot of various smaller systems running in Kubernetes, basically using it to have a PAAS to rapidly deploy stuff like Zammad. In order to have databases uniform and backed up, I use KubeDB, which offers both Elasticsearch, Postgres and memcached, so it was very easy to apply for Zammad. I would recommend making this a requirement for the Zammad Helm chart, to relieve some of the burden of the Helm Chart and focus on the actual Zammad deployment.

If someone who's well adversed with Zammad and have an interest in getting this improved is interested, please reach out and I will help with my mediocre Kubernetes knowledge :)

**Comment by monotek** [comment]
Splitting services is unfortunately not possible at the moment. See: 
https://github.com/zammad/zammad/issues/1601

Memcached might be replaced by rabbitmq at some point. Not sure if kubedb will add some benefit. I'll have a look...
