### ISSUE TITLE
Make nginx upload size configurable

### ISSUE THREAD

**Issue by ccws-betrieb** [zammad/zammad-helm#293]
https://github.com/zammad/zammad-helm/blob/48d187fa1f2b8d03e66a9dbdb4605a0d35fbc9a9/zammad/templates/configmap-nginx.yaml#L41

Please make the upload size configurable within zammadConfig.

**Comment by mgruner** [comment]
@ccws-betrieb great suggestion. Can you try #294 and see if this solves your issue?

**Comment by ccws-betrieb** [comment]
Problem solved. Thx.
