### ISSUE TITLE
cannot run zammad with microk8s

### ISSUE THREAD

**Issue by codingfunwoody** [zammad/zammad-helm#296]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm: v3.9.1
k8s: v1.30.5
microk8s: v1.12.2, 

**What happened**:
cannot run with microk8s, 

railserver, scheduler and websocket are stucked after 20240717152405_issue_5268_update_state_object_manager_attribute.rb 

![image](https://github.com/user-attachments/assets/0255c586-370d-456a-8096-411fd08a2ecf)
`
20240717152405_issue_5268_update_state_object_manager_attribute.rb

    from /opt/zammad/config/initializers/active_record_pending_migrations.rb:4:in `<main>'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/engine.rb:667:in `load'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/engine.rb:667:in `block in load_config_initializer'
    from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/notifications.rb:208:in `instrument'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/engine.rb:666:in `load_config_initializer'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/engine.rb:619:in `each'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/engine.rb:619:in `block in <class:Engine>'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/initializable.rb:32:in `instance_exec'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/initializable.rb:32:in `run'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/initializable.rb:61:in `block in run_initializers'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/initializable.rb:50:in `each'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/initializable.rb:50:in `tsort_each_child'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `call'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
    from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/initializable.rb:60:in `run_initializers'
    from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/application.rb:372:in `initialize!'
    from /opt/zammad/config/environment.rb:7:in `<top (required)>'
    from script/background-worker.rb:8:in `require'
    from script/background-worker.rb:8:in `<top (required)>'
    from /usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
    from /usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
    from /usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
    from /usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
    from /usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    from /usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    from /usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
    from /usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
    from /usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
    from /usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
    from /usr/local/bundle/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
    from /usr/local/bundle/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
    from /usr/local/bundle/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
    from /usr/local/bundle/bin/bundle:25:in `load'
    from /usr/local/bundle/bin/bundle:25:in `<main>'
Stream closed EOF for zammad/zammad-scheduler-869785745f-ldxdm (zammad-scheduler)
`

**What you expected to happen**:
start normally and can go localhost:8080

**How to reproduce it** (as minimally and precisely as possible):
install microk8s
enable addon hostpath-storage and helm
run microk8s helm upgrade --install zammad zammad/zammad -n zammad --create-namespace

do i need to enable something on microk8s? no idea what is 20240717152405_issue_5268_update_state_object_manager_attribute.rb
doing, many thanks for help

**Comment by codingfunwoody** [comment]
After i tried downgrade and upgrade back to latest version, it's work now.
i guess the init action cannot wait redis/elasticsearch pods ready so that it's error. Hope this help who cannot clean install the zammad with helm.

**Comment by mgruner** [comment]
There is an init job which needs to first finish for the deployments to be able to start up, and this itself requires the service containers like DB, redis and memcached. So some crashes during the startup/init phase are expected. Only if that permanently fails, there would be a bug that we need to look at.
