### ISSUE TITLE
Wrong VolumeBinding with "zammad-0" and "zammad-zammad-0"?

### ISSUE THREAD

**Issue by cyberrranger** [zammad/zammad-helm#45]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Version of Helm and Kubernetes**:
```
helm v3.2.1
kubelet v1.18.2 (microk8)
```

**What happened**:
i want to start a default helm install test

**What you expected to happen**:
can't start withot error show pictures vv

**How to reproduce it** (as minimally and precisely as possible):
`helm upgrade --install zammad zammad/zammad --namespace zammad`

**Anything else we need to know**:

![Screenshot 2020-05-28 11 43 30](https://user-images.githubusercontent.com/21671762/83126058-9d42c400-a0d8-11ea-9565-26496a5472bc.png)
![Screenshot 2020-05-28 11 43 42](https://user-images.githubusercontent.com/21671762/83126072-a0d64b00-a0d8-11ea-8177-1f3a0d5f04b1.png)

**Comment by monotek** [comment]
does microk8s provide pvc support?

**Comment by cyberrranger** [comment]
yes, show on my second screenshot

**Comment by monotek** [comment]
But it seems i can't mount your pvc. whyever. not a problem of the chart as it works in gke or a kind cluster for example.
