### ISSUE TITLE
Documentation/CRD for autowizard config

### ISSUE THREAD

**Issue by fredericOfTestfabrik** [zammad/zammad-helm#46]
FEATURE REQUEST

**Version of Helm and Kubernetes**:
irrelevant

**What happened**:

While experimenting with the helm chart, I noticed that there is a autowizard config that is able to configure most Settings out of the box. However I soon hit a dead end when i tried to configure an email channel using the autowizard, since I was unsure how the json of the autowizard should look like. 

**What you expected to happen**:

A Custom Resource Definition defining how the autowizard config should look like would greatly reduce confusion and would make it easier for users to setup their zammad instance. At least, a documentation that describes what fields can be set in the autowizard should be available.

**Comment by monotek** [comment]
I don't think a CRD, which extends the Kubernetes API, makes sense here.
We don't have a controller which could make use of a CRD.

In the end the json is only a config file representing an Zammad API call.
Some Zammad API docu can be found here: https://docs.zammad.org/en/latest/api/intro.html

Fore more info you might want to ask in the community forums.

**Comment by fredericOfTestfabrik** [comment]
Okay I will look into that. Unfortunately, the documentation seems very basic. I will switch to the community forums if I have any questions about that.
