### ISSUE TITLE
Problem after upgrading zammad from version 3.2 to 3.4

### ISSUE THREAD

**Issue by rmuehlbauer** [zammad/zammad-helm#48]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
helm version 3.2.4
Kubernetes 1.16.10 (Google Cloud GKE v1.16.10-gke.8)

**What happened**:
I'm upgrading a zammad 3.2 (helm chart zammad-1.2.1 / zammad/zammad-docker-compose:3.2.0-13) installation to zammad 3.4 (helm chart zammad-2.2.0 / zammad/zammad-docker-compose:3.4.0-11).
After the upgrade something weird happens to the user/groups/roles config. There are several problems I've noticed so far:
- unable to assign an existing ticket to another agent (list of agents is empty)
- "insufficient rights" to open my tickets
- cant see any tickets at all
- parts of the "roles" in the roles config menu seem to be gone
- ...

**What you expected to happen**:
user/groups/roles config should keep working. access to existing tickets should be available. ticket should be assignable to other agents

**How to reproduce it** (as minimally and precisely as possible):
What I did was:
1. installed zammad helm chart 2.2.0 in a new namespace (helm install zammad-test -n zammad-test zammad/zammad) and let the system initially come up.
2. made a database dump on the old installation (stopped the rails server before doing so)
3. shut down the rails server on the new installation
4. importing the db dump on the new postgresql pod (drop existing database, create an empty one, importing the db dump in the new, empty database)
5. starting the rails pod again and let it go through all init container (works without problems) and wait until the system is ready
6. logon on to the new system (users from the old system are working) and "click around" a bit - especially try to reassign tickets and open/edit/save grous/roles configs.
7. Very soon I can not view any tickets anymore, parts of "edit users" and "edit roles" dialogues are gone

**Anything else we need to know**:
I tried it now several times to import different db dump created on the the 3.2 system to import on the 3.4 system.
The dumping/importing itself is running without problems. Also the app server starts without issues on the newly imported database - only after a short while, the system seems to degenerate.
I'm wondering it there were some changes to the db schema in 3.4 that are somehow missing?
I cant find any obvious errors in the logs (not on the database and also not zammad app server)

**Comment by monotek** [comment]
Have you tried to install 3.2, import the backup, update to 3.3 and then to 3.4?

**Comment by rmuehlbauer** [comment]
if you call it a upgrade to pull down the zammad 3.2 docker container(s) and bring up a 3.3/3.4 one(s) instead, then the answer is yes - I've tried to upgrade that way for several times.
I've also left a message over at [community.zammad.com](https://community.zammad.org/t/upgrading-zammad-from-version-3-2-to-version-3-4/5065).
Long story short: I could solve my issues by running a db:init before importing the db dump - it seems like there is something missing in the db when you just export on 3.2 and import on 3.4... db:init could solve that issue.
As fas as of now, I was not able to find out where exactly the problem came from - only that db:init obviously solved it. 
If we could find out the root cause of the problem, maybe zammad's postgresql init container could take care of this...

**Comment by monotek** [comment]
Sorry, we weren't able to reproduce...
