### ISSUE TITLE
Safe to change image

### ISSUE THREAD

**Issue by caesarcxiv** [zammad/zammad-helm#49]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
1.18

Is there any issue in upgrading the docker image to 3.5 ?

**Comment by monotek** [comment]
Vacation ;-)

**Comment by monotek** [comment]
3.5. is still in the develop branch.
You can use it manually but chart will be updated only if it becomes stable.
Nevertheless there will be an update to the latest version soon in: https://github.com/zammad/zammad-helm/pull/53
