### ISSUE TITLE
Scaling statefulset zammad / jobs run on multiple instances at the same time

### ISSUE THREAD

**Issue by caesarcxiv** [zammad/zammad-helm#51]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
1.18.6
image 3.4.0-18

**What happened**:
When scaling zammad statefulset it appears the scheduler runs the same jobs at the same time. 

This results in duplicate email tickets etc.

**What you expected to happen**:

scheduler validates jobs are not already running.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by monotek** [comment]
You can't scale horizontally.
That's the reason the replica value is not configurabke. In the values.yaml.

See: https://github.com/zammad/zammad-helm/issues/28

**Comment by bronger** [comment]
Given that the upstream has improved, is there any update on this?

**Comment by monotek** [comment]
Which improvement are your referring to?

**Comment by bronger** [comment]
Concerning horizontal scaling.

**Comment by monotek** [comment]
As far as i know there were no improvements.

**Comment by bronger** [comment]
Then I misunderstood it, sorry.

**Comment by bronger** [comment]
BTW, it was this comment: https://github.com/zammad/zammad/issues/1601#issuecomment-878209560

But it says “makes it easier”, so there are probably still things to do.

**Comment by monotek** [comment]
In Zammad 5. Which is not available yet...

**Comment by mrad-bilel** [comment]
Hello,

@monotek 
cc @bronger 
Does the horizontal scaling is now supported in zammad helm chart zammad-6.0.1 ?

**Comment by monotek** [comment]
No.
