### ISSUE TITLE
Refactor elasticsearch-init

### ISSUE THREAD

**Issue by caesarcxiv** [zammad/zammad-helm#54]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**What happened**:
When restarting zammad, in attempts to reset the scheduler sidecar, the elasticsearch-init runs for every ticket in the system causes extreme restart times that get longer by the hour.

**What you expected to happen**:
Zammad immediately resets and elasticsearch is reindexed via a job.

**How to reproduce it** (as minimally and precisely as possible):
Restart zammad stateful set

**Anything else we need to know**:

**Comment by monotek** [comment]
Will be fixed with: https://github.com/zammad/zammad-helm/pull/60

**Comment by monotek** [comment]
for reference: https://github.com/zammad/zammad/issues/3219
