### ISSUE TITLE
Ability to add custom nginx configuration

### ISSUE THREAD

**Issue by cabillman** [zammad/zammad-helm#69]
Would you be willing to accept a patch that allows for inserting additional nginx configuration into the nginx configmap from helm values?

We run our instance of Zammad behind a Google IAP and would like the ability to rewrite some of the headers before it hits zammad.  I'm specifically targeting this area - https://github.com/zammad/zammad-helm/blob/master/zammad/templates/configmap-nginx.yaml#L52

I'm trying avoid the need to run an additional instance of nginx in front for the purpose of rewriting a few headers.

**Comment by monotek** [comment]
We have something similar already in the docker-compose entrypoint. 
See: https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh#L16

I could think of somethinf like this for the helm chart too.

So yes, PR welcome :)
