### ISSUE TITLE
Feature Request: Disable elasticsearch-init 

### ISSUE THREAD

**Issue by grafjo** [zammad/zammad-helm#74]
I know - it's not recommended to run zammad without elasticsearch - the documentation says that it's possible for small teams etc.
Right now, it's not possible to disable elasticsearch config / the elasticsearch-init container in the helm chart.
Let me know if you like the idea, so I can pull request this feature.

**Comment by monotek** [comment]
Yes, the init part could be disabled, when elasticsearch.enabled = false.
PR welcome :)

**Comment by grafjo** [comment]
ok - I'll provide a PR!
