### ISSUE TITLE
API : Error ID rn0Mel5q: Please contact your administrator

### ISSUE THREAD

**Issue by mrad-bilel** [zammad/zammad-helm#77]
---

**Is this a BUG REPORT **:

**Version of Helm and Kubernetes**:

Chart version: zammad-3.0.0
Kubernetes version: v1.15.11
DB:Postgresql 11.5

**What happened**:
we get a random error when we perofrm a search for Tickets  / groups .

“Error ID rn0Mel5q: Please contact your administrator”

DB logs 

DataBase Logs :
[2020-12-24T07:49:40.588575 #1-69853656656080] ERROR – : Error ID dd-TPKCZ: PG::InFailedSqlTransaction: ERROR: current transaction is aborted, commands ignored until end of transaction block
: SELECT “active_job_locks”.* FROM “active_job_locks” WHERE “active_job_locks”.“lock_key” = $1 LIMIT $2 FOR UPDATE

**What you expected to happen**:

Get the list of tickets / groups

**Comment by monotek** [comment]
@thorsteneckel 
Any idea what could be the problem?
Failed migration?

**Comment by thorsteneckel** [comment]
Is there more about it in the log @mrad-bilel ? A backtrace would help a lot. Maybe some relevant log lines before that one, too.
