### ISSUE TITLE
Elastic reindex every start

### ISSUE THREAD

**Issue by caesarcxiv** [zammad/zammad-helm#78]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**: latest helm chart with 1.19

**What happened**:
Starting the statefull set always starts an elastic full index causing our startup time to increase as time / usage exands

**What you expected to happen**:

Full index is not performed every start

**How to reproduce it** (as minimally and precisely as possible):

scale down and up the ss

**Anything else we need to know**:

![image](https://user-images.githubusercontent.com/13050060/106320847-6dd4f000-6241-11eb-8402-f8c48b024e07.png)

**Comment by monotek** [comment]
https://github.com/zammad/zammad-helm/blob/master/zammad/values.yaml#L52
