### ISSUE TITLE
How to install zammad as NONROOT user for a private cloud

### ISSUE THREAD

**Issue by ajeetratnu** [zammad/zammad-helm#81]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 
output of helm version commad:
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

output of kubectl version commad:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**What happened**: Zammad is developed as Root User which are not allowed in private cloud for security reason.

**What you expected to happen**: To be able to install zammad as NONROOT user

**How to reproduce it** (as minimally and precisely as possible): NA

**Anything else we need to know**:
I tried to create new images from the current image and just adding USER 1000 to start as.
My dockerfile has only two lines:
FROM image-name-here
USER 1000

With this I can deploy but the pods don't come up as internally it get into lots of other issues as the user is NOT root user.

**Comment by monotek** [comment]
Currently [gosu](https://github.com/tianon/gosu) is used to drop root privileges and become zammad user, when containers are started. Background is, that nginx needs root user by default to start.

See railssserver for example: 
https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh#L149

PR for running all containers as zammad user without gosu is in progress: https://github.com/zammad/zammad-docker-compose/pull/189

**Comment by monotek** [comment]
Will be fixed with: https://github.com/zammad/zammad-helm/pull/82
