### ISSUE TITLE
How To Configure Zammad with exsisting postgress DB / or AWS RDS 

### ISSUE THREAD

**Issue by dimuit86** [zammad/zammad-helm#89]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:

Version 3

**What happened**:
I'm testing Zammad on Kubernetes using Helm charts.  It works fine. But, I already have a separate Postgres database.

**What you expected to happen**:

I want to integrate Zammad with an existing Postgres DB, or Amazon RDS DB 

**Anything else we need to know**:

Yes, I want to know how to set up Zammad on Kubernetes with a separate Postgres database. Hope anyone will help me with this.

**Comment by monotek** [comment]
https://github.com/zammad/zammad-helm/blob/master/zammad/values.yaml#L228-L230
