### ISSUE TITLE
Allow modification of pooled connections / service crash

### ISSUE THREAD

**Issue by caesarcxiv** [zammad/zammad-helm#98]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
3, 1.20

**What happened**:
zammad-scheduler pod goes into crashloopbackoff crashing entire service

**What you expected to happen**:
zammad-scheduler stays up

**How to reproduce it** (as minimally and precisely as possible):
Please create an option to increase the workers and connection pool. The current limit of 5 on the zammad-scheduler causes the entire service to crash leading to service disruption. 

 ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.023 seconds); all pooled connections were in use. 

Pod restarts

**Anything else we need to know**:

**Comment by RegisHubelia** [comment]
I have the same issue with version 12+ - the "new" separated scheduler keeps complaining about pool size.  Error is Can't reconnect to database #<ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use>

**Comment by mgruner** [comment]
@RegisHubelia can you please share the value of `DATABASE_URL` that gets used by the containers?

**Comment by RegisHubelia** [comment]
Sure - looks like this postgres://user:$(POSTGRESQL_PASS)@cluster.namespace.svc:5432/database?pool=200.  Tried with 100, 200, 500 - and my cluster can accept up to 1000, but no dime...  The scheduler pod always end up in crashloop backoff - complaining of the error above...

**Comment by MrGeneration** [comment]
What's the `max_connection` setting of your postgresql container? It won't help at all to ramp up your pool to such high values (50 is the default and in 98% of use cases well enough) if your database server doesn't allow that many connections in general.

**Comment by RegisHubelia** [comment]
As stated, I set the max_connection to 1000 (for testing purposes, I am well aware that the current settings aren't optimal, but for the sake of testing, I ramped those values up to see what happens and help in the troubleshooting).  This wasn't an issue pre v12 from what I can tell...

**Comment by RegisHubelia** [comment]
I actually changed the max_connection of postgres to 2000 - and it seems to be fine now.  A bit high to my opinion, but for now it works much better.

**Comment by RegisHubelia** [comment]
Eventually tough, it ends up doing the same, just takes longer...

**Comment by RegisHubelia** [comment]
For those who get the same issue, because the scheduler is now separated from the zammad instance, I had to allocate ressources requests/limits to the scheduler.  It used to be on the same instance therefore they were sharing the ressources, but it seems that the reason for the scheduler to give the pool error is because there wasn't enough ressources for the pools to come up.  Seems like all is good now.
